server:
  command: "php /app/worker.php"

http:
  address: :8080
  pool:
    num_workers: 4
    max_jobs: 64

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/app" ]
