name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        docker-compose: ["1.27.4", "1.9.0"]
    name: Docker Compose v${{ matrix.docker-compose }}
    steps:
      - uses: actions/checkout@master

      - name: Setup docker-compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/${{ matrix.docker-compose }}/docker-compose-Linux-x86_64 > docker-compose
          chmod +x docker-compose

      - name: Initialize
        run: ./task init

      - name: Build
        run: ./task up

      - name: Test http request
        run: curl http://127.0.0.1:8080
